<h1><?= $tytul ?></h1>

<div class="row">
    <div class="col-lg-4">
        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
        <!--  Label get pobieranie danych z formularza  -->
            <?= $this->formLabel($form->get('nazwaPliku')) ?>
            <?= $this->formText($form->get('nazwaPliku')) ?>
            <?= $this->formElementErrors($form->get('nazwaPliku'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('trescPliku')) ?>
            <?= $this->formTextarea($form->get('trescPliku')) ?>
            <?= $this->formElementErrors($form->get('trescPliku'), ['class' => 'help-block']) ?>
        </div>
        <?= $this->formSubmit($form->get('zapisz')) ?>

        <?= $this->form()->closeTag($form) ?>
    </div>
</div>